export declare function testCoreBanking(): string;
export { getGreeting } from '@banking-sim/common';
export * from './models/account';
export * from './services/customer-service';
export * from './services/account-service';
export * from './services/database-service';
export * from './services/consent-service';
export * from './services/transaction-service';
export * from './data/in-memory-db';
export { seedBankData } from './data/seed-data';
